version: "3.9"
services:
  web:
    build: ./web
    container_name: python
    ports:
      - "5000:5000"
    volumes:
      - ./web:/code
      - ${PWD}/README.MD:/code/README.md
    env_file:
      - ./.env.dev
