services:
  web:
    build: ./web
    container_name: python
    ports:
      - "5000:5000"
    volumes:
      - ./web:/code
      - ${PWD}/README.MD:/code/README.md
      - ${PWD}/google_credentials.json:/code/app/google_credentials.json
    env_file:
      - ./.env.dev
