services:
  carbon:
    build: ./web
    container_name: carbon
    expose:
      - 5000
    volumes:
      - ${PWD}/README.md:/code/README.md
      - ${PWD}/google_credentials.json:/code/app/google_credentials.json
    env_file:
      - ./.env.prod
    command: gunicorn --max-requests 5000 --bind 0.0.0.0:5000 manage:app --timeout 120

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "1337:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - carbon

volumes:
  dbdata:
